name: change_env

on:
  push:
    branches:
      - main
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Setup JDK 11 for Sonar Cloud
        uses: actions/setup-java@v1
        with:
            java-version: 11
      
      - name: Maven Build
        run: mvn clean install -DskipTests=true
      
  deploy:
    environment: PROD
    needs: build
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Deployment 
        run: echo Run PROD deployment.

  deploy1:
    environment: PROD1
    needs: deploy
    name: Deployment1
    runs-on: ubuntu-latest
    steps:
      - name: Deployment1
        run: echo Run PROD1 deployment
 
  deploy2:
    environment: PROD2
    needs: deploy1
    name: Deployment2
    runs-on: ubuntu-latest
    steps:
      - name: Deployment2 

  deploy3:
    environment: PROD3
    needs: deploy2
    name: Deployment3
    runs-on: ubuntu-latest
    steps:
      - name: Deployment3 
        run: echo Run PROD3 deployment        
  
